version: "3.8"

services:
  api:
    build: .
    container_name: "qa-api-cont"
    ports:
      - "8080:8080"
    volumes:
      - cont_logs:/app/logs
    restart: on-failure
  
  ui:
    image: nginx
    container_name: "qa-ui-cont"
    ports:
      - "9090:80"
    volumes:
      - ./ui:/usr/share/nginx/html
    restart: on-failure
    depends_on:
      - api

  db:
    image: mysql:9.0.0
    container_name: "qa-db-cont"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    ports:
      - "9999:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure

volumes:
  cont_logs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./cont_logs
